import { build } from 'esbuild';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Bundle the MCP App iframe into ONE self-contained HTML string module.
 * No external requests survive: ext-apps is bundled in, CSS and JS are
 * inlined, and the result is emitted as src/server/apphtml.generated.ts
 * so the server can serve it as the ui://mafia/app.html resource.
 */

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const js = await build({
  entryPoints: [join(root, 'src/app/main.ts')],
  bundle: true,
  format: 'iife',
  minify: true,
  target: 'es2020',
  write: false,
  logLevel: 'silent',
});
const bundle = js.outputFiles[0].text;

const css = readFileSync(join(root, 'src/app/styles.css'), 'utf8');
const template = readFileSync(join(root, 'src/app/template.html'), 'utf8');

const html = template
  .replace('/*__CSS__*/', () => css)
  .replace('/*__JS__*/', () => bundle);

// Guard: a strict iframe CSP means any external fetch would break at the
// worst possible moment (on stage). Refuse to emit HTML that references one.
const externalRef = /<(script|link|img|iframe)[^>]+(src|href)\s*=\s*["']https?:\/\//i.exec(html);
if (externalRef) {
  console.error(`build-app: external reference found: ${externalRef[0]}`);
  process.exit(1);
}

const out = `// GENERATED by scripts/build-app.mjs — do not edit. Rebuild with: npm run app:build
export const APP_HTML: string = ${JSON.stringify(html)};
`;

mkdirSync(join(root, 'src/server'), { recursive: true });
writeFileSync(join(root, 'src/server/apphtml.generated.ts'), out);
console.log(`build-app: ${(html.length / 1024).toFixed(1)} KiB inlined into src/server/apphtml.generated.ts`);
